---
language: node_js
node_js:
  - "6.9.1"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=ember-2.9
  - EMBER_TRY_SCENARIO=ember-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta

matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - phantomjs --version

install:
  - yarn install --no-lockfile
  - bower install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
